// <auto-generated />
using ApiServer.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using System;

namespace WEBApiSite.Migrations
{
    [DbContext(typeof(CompanySiteDataContexts))]
    [Migration("20181009093135_Dbmigration")]
    partial class Dbmigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Entity.TableModel.T_User", b =>
                {
                    b.Property<string>("userName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32);

                    b.Property<DateTime>("lastLoginTime");

                    b.Property<int>("loginCount");

                    b.Property<string>("passWord")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<int>("status");

                    b.Property<string>("userId")
                        .IsRequired()
                        .HasMaxLength(32);

                    b.Property<string>("userRole")
                        .HasMaxLength(32);

                    b.Property<int>("wrongCount");

                    b.HasKey("userName");

                    b.ToTable("t_User");
                });
#pragma warning restore 612, 618
        }
    }
}
